version: '3.9'
networks:
  app-tier:
    driver: bridge

services:
  aliaser:
    container_name: aliaser
    build: .
    image: aliaser:v1
    ports:
      - '5000:5000'
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=False
      - BACKUP_SCHEDULE=3600
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - GIT_MODE=GITHUB
      - GITHUB_RAW_FILE_LOCATION=
      - GITHUB_REPO=
      - GITHUB_BRANCH=
      - GITHUB_USER=
      - GITHUB_TOKEN=
      - GITLAB_HOST=
      - GITLAB_PROJECT_TOKEN=
      - GITLAB_PROJECT_ID=
      - GITLAB_PROJECT_BRANCH=

  cache:
    image: redis